# Generated by Django 5.1.6 on 2025-02-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_update_room_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='decription',
            new_name='description',
        ),
    ]
